# Generated by Django 3.2 on 2024-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('consent_obtained', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('reframe_final_id', models.IntegerField()),
                ('age_range', models.TextField(default='')),
                ('gender', models.TextField(default='')),
                ('race', models.TextField(default='')),
                ('income', models.TextField(default='')),
                ('education', models.TextField(default='')),
                ('population', models.TextField(default='')),
                ('problems', models.TextField(default='')),
                ('treatment', models.TextField(default='')),
                ('prior_experience', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('thought_id', models.IntegerField(default=0)),
                ('belief', models.TextField(default='')),
                ('emotion', models.TextField(default='')),
                ('emotion_strength', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('feedback', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flag_Inappropriate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('reframe', models.TextField(default='')),
                ('delete_label', models.IntegerField(default=0)),
                ('reason', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Next_Check_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('step_number_from', models.IntegerField(default=-1)),
                ('error_type', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenAI_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('input', models.TextField(default='')),
                ('response_no', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('reframe_final_id', models.IntegerField()),
                ('believable', models.TextField(default='')),
                ('stickiness', models.TextField(default='')),
                ('helpfulness', models.TextField(default='')),
                ('learnability', models.TextField(default='')),
                ('belief_1', models.TextField(default='')),
                ('emotion_strength_1', models.TextField(default='')),
                ('belief_2', models.TextField(default='')),
                ('emotion_strength_2', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reframe_Final',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reframe_final_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('reframe_selected_id', models.IntegerField(default=0)),
                ('reframe_final', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reframe_Selected',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reframe_selected_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('reframes_generated_id', models.IntegerField(default=0)),
                ('reframe_selected', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reframes_Generated',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reframes_generated_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('thinking_trap_selected_id', models.IntegerField(default=0)),
                ('reframe_generated', models.TextField(default='')),
                ('reframe_generated_prompt_type', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reframes_More_Help',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reframes_more_help_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('original_reframe', models.TextField(default='')),
                ('reframe_generated', models.TextField(default='')),
                ('reframe_generated_prompt_type', models.TextField(default='')),
                ('more_context', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refresh_Btn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Safety_Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('text', models.TextField(default='')),
                ('type', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show_More_Thinking_Traps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('num_thinking_trap_shown', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situation_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('thought_id', models.IntegerField(default=0)),
                ('situation', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Start_Over',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_thought_record_id', models.IntegerField()),
                ('new_thought_record_id', models.IntegerField()),
                ('step_number_from', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('step_number_from', models.IntegerField(default=-1)),
                ('step_number_to', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thinking_Trap_Generated',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thinking_trap_generated_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('situation_id', models.IntegerField(default=0)),
                ('thinking_trap_generated_cat', models.TextField(default='')),
                ('thinking_trap_generated_other_cat', models.TextField(default='')),
                ('thinking_trap_generated_perc', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thinking_Trap_Selected',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thinking_trap_selected_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('thinking_trap_generated_id', models.IntegerField(default=0)),
                ('thinking_trap_selected', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_record_id', models.IntegerField()),
                ('thought', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThoughtRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('referral_code', models.TextField(default='')),
                ('skip_step', models.TextField(default='')),
                ('remove_negative_feeling', models.IntegerField(default=0)),
                ('prompt_to_use', models.TextField(default='')),
                ('refresh_btn', models.IntegerField(default=0)),
                ('more_suggestions_btn', models.IntegerField(default=0)),
                ('descriptive_thought_Q', models.IntegerField(default=0, null=True)),
                ('loading_time', models.FloatField(default=0, null=True)),
                ('A_A', models.IntegerField(default=0, null=True)),
                ('multiple_cognitive_distortions', models.IntegerField(default=0, null=True)),
                ('extra_q', models.IntegerField(default=0, null=True)),
                ('emotion_questions', models.TextField(default='', null=True)),
                ('personalize', models.IntegerField(default=0, null=True)),
                ('readable', models.IntegerField(default=0, null=True)),
                ('psychoeducation', models.IntegerField(default=0, null=True)),
                ('ai', models.IntegerField(default=0, null=True)),
                ('include_emotions', models.IntegerField(default=0, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URL_Clicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought_record_id', models.IntegerField()),
                ('url_text', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('ip_address', models.TextField(default='')),
                ('condition', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
