"""
Django settings for overcoming_thinking_traps project.

Generated by 'django-admin startproject' using Django 3.2.
Upgraded to Django 4.2.26 LTS (2024-12-10)

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def get_env_variable(var_name, default=None):
    """Get environment variable or return default/raise exception"""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY_MHA_TOOL')

# SECURITY WARNING: don't run with debug turned on in production!
# Allow DEBUG to be set via environment variable for local development
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS: Use environment variable or default to specific domains
ALLOWED_HOSTS_ENV = get_env_variable('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Default production domains if not set via environment variable
    ALLOWED_HOSTS = [
        'screening.mhanational.org',
        'mhanational.org',
        'mhanationalstg.wpengine.com',
        'mhatools-ott.azurewebsites.net',  # Azure App Service default domain
        'mhatools-ott-staging.azurewebsites.net',  # Staging slot
    ]

CSP_IMG_SRC = ("'unsafe-inline'", "https://raw.githubusercontent.com", "https://www.w3.org", "data:")

CSP_STYLE_SRC = ("'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdn", "https://cdnjs.cloudflare.com", "https://code.jquery.com", "https://fonts.googleapis.com", "'self'")



# CSP_SCRIPT_SRC: Removed 'unsafe-eval' for security (kept 'unsafe-inline' temporarily - requires template refactoring)
CSP_SCRIPT_SRC = ("'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdn", "https://cdnjs.cloudflare.com", "https://code.jquery.com", "https://fonts.googleapis.com", "https://github.com", "https://www.googletagmanager.com", "https://www.google-analytics.com/", "'self'")

# CSP_CONNECT_SRC: Allow connections to CDNs for source maps and API calls
CSP_CONNECT_SRC = ("'unsafe-inline'", "https://www.google-analytics.com/", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", "'self'")


CSP_SCRIPT_SRC_ELEM = ("'unsafe-inline'", "https://cdn.rawgit.com", "https://cdn.jsdelivr.net", "https://cdn", "https://cdnjs.cloudflare.com", "https://code.jquery.com", "https://fonts.googleapis.com", "https://github.com", "https://www.googletagmanager.com", "https://www.google-analytics.com/", "'self'")



CSP_FONT_SRC = ("'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdn", "https://cdnjs.cloudflare.com", "https://code.jquery.com", "https://fonts.googleapis.com", "https://fonts.gstatic.com")

CSP_FRAME_ANCESTORS = ("'self'", 'http://megavolt.cs.washington.edu:15000', 'https://mhanationalstg.wpengine.com', 'https://screening.mhanational.org', 'https://mhanational.org')

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'diy_tool.apps.DiyToolConfig',
	# 'study.apps.StudyConfig',
]

# CSRF Protection
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False  # Must be False for SameSite=None to work with some browsers
CSRF_TRUSTED_ORIGINS = ['https://mhanationalstg.wpengine.com', 'https://screening.mhanational.org', 'https://mhanational.org']

# Session Security
SESSION_COOKIE_SAMESITE = 'None'  # Required for cross-origin requests
SESSION_COOKIE_SECURE = True  # Only send cookies over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies (XSS protection)


# Session security: Reduced from 1 year to 30 days for better security
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days (reduced from 1 year)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True


SESSION_ENGINE = "django.contrib.sessions.backends.db"

MIDDLEWARE = [
	'csp.middleware.CSPMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	# XFrameOptionsMiddleware removed - using CSP_FRAME_ANCESTORS instead for better control
]

# Security Settings
# HTTPS/SSL Configuration
# Disable SSL redirect for local development (no HTTPS locally)
DISABLE_SSL_REDIRECT = os.environ.get('DISABLE_SSL_REDIRECT', 'False').lower() in ('true', '1', 'yes')
SECURE_SSL_REDIRECT = not DISABLE_SSL_REDIRECT  # Redirect HTTP to HTTPS (disabled for local dev)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # For Azure App Service behind proxy

# HSTS (HTTP Strict Transport Security) - Only enable in production
if not DISABLE_SSL_REDIRECT:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Disable HSTS for local development
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Content Security (always enabled)
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filter
# X_FRAME_OPTIONS disabled - using CSP_FRAME_ANCESTORS instead for cross-origin iframe embedding
# CSP_FRAME_ANCESTORS allows embedding from screening.mhanational.org and other trusted domains
X_FRAME_OPTIONS = None  # Disabled to allow CSP_FRAME_ANCESTORS to control iframe embedding
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information sent with requests

# Only set proxy SSL header if running on Azure App Service
if os.environ.get('WEBSITE_SITE_NAME'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Consent Form Configuration
# Set REQUIRE_CONSENT=False to disable consent form (useful for testing)
# Defaults to True for production safety
REQUIRE_CONSENT = os.environ.get('REQUIRE_CONSENT', 'True').lower() in ('true', '1', 'yes')

ROOT_URLCONF = 'overcoming_thinking_traps.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(SETTINGS_PATH, 'diy_tool', 'templates'), os.path.join(SETTINGS_PATH, 'templates'),],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'overcoming_thinking_traps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
	'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('OTT_DBNAME'),
        'USER': get_env_variable('OTT_DBUSER'),
        'PASSWORD': get_env_variable('OTT_DBPASS'),
        'HOST': get_env_variable('OTT_DBHOST'),
		'PORT': '5432',
		# Azure PostgreSQL connection settings
		'CONN_MAX_AGE': 600,  # Connection pooling: reuse connections for 10 minutes
		# SSL: Only require for Azure PostgreSQL, not local Docker
		'OPTIONS': {
			'sslmode': 'prefer',  # Prefer SSL but don't require (works for local Docker)
		} if DEBUG else {
			'sslmode': 'require',  # Require SSL for Azure PostgreSQL in production
		},
		# Connection timeout settings
		'CONN_HEALTH_CHECKS': True,
    }
	# 'default': {
	# 	'ENGINE': 'django.db.backends.sqlite3',
	# 	'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	# }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATICFILES_DIRS = (str(BASE_DIR.joinpath('static')),)
# STATIC_URL = '/static/'

# AUTH_USER_MODEL = "users.CustomUser"

# AUTHENTICATION_BACKENDS = ['users.auth_backend.PasswordlessAuthBackend',]

DEFAULT_AUTO_FIELD ='django.db.models.AutoField' 

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), )
# STATIC_ROOT: Directory where collectstatic will gather all static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# LOGIN_REDIRECT_URL = '/study/home'
# LOGIN_URL = '/users/login'